AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create three Amazon EC2 instances'

Resources:
  Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04823729c75214919  # Replace with your desired AMI ID
      KeyName: Learning-VPC-Key  # Replace with your EC2 key pair name
      NetworkInterfaces:
        - DeviceIndex: 0 
          GroupSet:
            - sg-0b314140377618bdb  # Replace with your desired security group ID
          SubnetId: subnet-0b9fe786bd5eb1966  # Replace with the ID of the subnet you created

  Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04823729c75214919
      KeyName: Learning-VPC-Key
      NetworkInterfaces:
        - DeviceIndex: 0
          GroupSet:
            - sg-0b314140377618bdb
          SubnetId: subnet-0b9fe786bd5eb1966

  Instance3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04823729c75214919
      KeyName: Learning-VPC-Key
      NetworkInterfaces:
        - DeviceIndex: 0
          GroupSet:
            - sg-0b314140377618bdb
          SubnetId: subnet-0b9fe786bd5eb1966
